<%@ Page Title="" Language="C#" MasterPageFile="~/Prog6/Prog6MasterPage.Master" AutoEventWireup="true" CodeBehind="Page Updating.aspx.cs" Inherits="Prog1.Prog5.Page_Updating" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPH1" runat="server">

       <div class="center">
           <asp:DetailsView ID="dtlProduct" runat="server" CellPadding="4" GridLines="None" Height="50px" Width="125px" AllowPaging="True" OnPageIndexChanging="DetailsView1_PageIndexChanging" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="ProductID" DataSourceID="SqlDataSource1" OnItemDeleting="dtlProduct_ItemDeleting" OnItemInserting="dtlProduct_ItemInserting1" OnItemUpdating="dtlProduct_ItemUpdating1" ForeColor="#333333">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <CommandRowStyle BackColor="#E2DED6" Font-Bold="True" />
                <EditRowStyle BackColor="#999999" />
                <FieldHeaderStyle BackColor="#E9ECF1" Font-Bold="True" />
                <Fields>
                    <asp:BoundField DataField="ProductID" HeaderText="ProductID" ReadOnly="True" SortExpression="ProductID" />
                    <asp:BoundField DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" />
                    <asp:BoundField DataField="UnitPrice" HeaderText="UnitPrice" SortExpression="UnitPrice" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                </Fields>
                <FooterStyle BackColor="#5D7B9D" ForeColor="White" Font-Bold="True" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                    <PagerSettings FirstPageText="First" LastPageText="Last" NextPageText="Next" PreviousPageText="Previous" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />

            </asp:DetailsView>
           <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:UWPCS3870ConnectionString %>" SelectCommand="SELECT * FROM [Product]" DeleteCommand="DELETE FROM [Product] WHERE ProductID = '@ProductID'" InsertCommand="INSERT INTO Product(ProductID, ProductName, UnitPrice, Description)
                    values (@ProductID, @ProductName, @UnitPrice, @Description)" UpdateCommand="UPDATE Product SET ProductName = '@ProductName', UnitPrice = '@UnitPrice', Description = '@Description' 
WHERE (ProductID = '@ProductID')"></asp:SqlDataSource>
           <asp:TextBox ID="txtMsg" runat="server" Height="82px" Width="163px"></asp:TextBox>
       </div>
    </asp:Content>