<%@ Page Title="" Language="C#" MasterPageFile="~/SiteMaster.Master" AutoEventWireup="true" CodeBehind="Checkout.aspx.cs" Inherits="PVille_Market.Checkout" %>
<asp:Content ID="Content1" ContentPlaceHolderID="Master" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">

    <div style="height: 235px; width: 488px; text-align: center; margin-left: 251px">
        <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="ProductId" DataSourceID="SqlDataSource1" Height="84px" PageSize="5" style="text-align: center; margin-top: 0px" Width="483px">
            <Columns>
                <asp:BoundField DataField="ProductId" HeaderText="ProductId" ReadOnly="True" SortExpression="ProductId" />
                <asp:BoundField DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" />
                <asp:BoundField DataField="ProductPrice" HeaderText="ProductPrice" SortExpression="ProductPrice" />
                <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
            </Columns>
        </asp:GridView>
        <asp:Label ID="Label1" runat="server" Font-Bold="True" Font-Names="Arial Black" height="27px" Text="Total is :" width="82px"></asp:Label>
        <asp:TextBox ID="TextBox1" runat="server" ReadOnly="True"></asp:TextBox>
        <asp:Button ID="btnCheckOut" runat="server" OnClick="btnCheckOut_Click" style="margin-top: 0px" Text="CheckOut" />
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:PvilleMarketConnectionString %>" DeleteCommand="DELETE FROM [Cart] WHERE [ProductId] = @ProductId" InsertCommand="INSERT INTO [Cart] ([ProductId], [ProductName], [ProductPrice], [Quantity]) VALUES (@ProductId, @ProductName, @ProductPrice, @Quantity)" SelectCommand="SELECT * FROM [Cart] ORDER BY [ProductId]" UpdateCommand="UPDATE [Cart] SET [ProductName] = @ProductName, [ProductPrice] = @ProductPrice, [Quantity] = @Quantity WHERE [ProductId] = @ProductId">
            <DeleteParameters>
                <asp:Parameter Name="ProductId" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="ProductId" Type="Int32" />
                <asp:Parameter Name="ProductName" Type="String" />
                <asp:Parameter Name="ProductPrice" Type="Decimal" />
                <asp:Parameter Name="Quantity" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="ProductName" Type="String" />
                <asp:Parameter Name="ProductPrice" Type="Decimal" />
                <asp:Parameter Name="Quantity" Type="Int32" />
                <asp:Parameter Name="ProductId" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </div>

</asp:Content>
