<%@ Page Title="" Language="C#" MasterPageFile="~/Prog5/MasterPage.Master" AutoEventWireup="true" CodeBehind="Page Updating.aspx.cs" Inherits="Prog1.Prog5.Page_Updating" %>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPH1" runat="server">

       <div class="center">
           <asp:DetailsView ID="dtlProduct" runat="server" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical" Height="50px" Width="125px" AllowPaging="True" OnPageIndexChanging="DetailsView1_PageIndexChanging" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateInsertButton="True" AutoGenerateRows="False" DataKeyNames="ProductID" DataSourceID="SqlDataSource1">
                <AlternatingRowStyle BackColor="#DCDCDC" />
                <EditRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                <Fields>
                    <asp:BoundField DataField="ProductID" HeaderText="ProductID" ReadOnly="True" SortExpression="ProductID" />
                    <asp:BoundField DataField="ProductName" HeaderText="ProductName" SortExpression="ProductName" />
                    <asp:BoundField DataField="UnitPrice" HeaderText="UnitPrice" SortExpression="UnitPrice" />
                    <asp:BoundField DataField="Description" HeaderText="Description" SortExpression="Description" />
                </Fields>
                <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                    <PagerSettings FirstPageText="First" LastPageText="Last" Mode="NextPreviousFirstLast" NextPageText="Next" PreviousPageText="Previous" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <RowStyle BackColor="#EEEEEE" ForeColor="Black" />

            </asp:DetailsView>
           <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:UWPCS3870ConnectionString %>" SelectCommand="SELECT * FROM [Product]" DeleteCommand="DELETE FROM [Product] WHERE ProductID = '@ProductID'" InsertCommand="INSERT INTO Product(ProductID, ProductName, UnitPrice, Description)
                    values (@ProductID, @ProductName, @UnitPrice, @Description)" UpdateCommand="UPDATE Product SET ProductName = '@ProductName', UnitPrice = '@UnitPrice', Description = '@Description' 
WHERE (ProductID = '@ProductID')"></asp:SqlDataSource>
           <asp:TextBox ID="txtMsg" runat="server" Height="82px" Width="163px"></asp:TextBox>
       </div>
    </asp:Content>